sudo: required

services:
  - docker
  
language: node_js
node_js:
  - "6"
  
notifications:
  email:
    on_success: never
    on_failure: always
    
before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine=17.04.0~ce-0~ubuntu-trusty > /dev/null

install:
  - npm install

script:
  - npm test
  
after_success:
  - npm i -g codecov
  - codecov -f coverage/lcov.info
  
