sudo: required

services:
  - docker
  
language: node_js
node_js:
  - "6"
  
notifications:
  email:
    on_success: never
    on_failure: always
    
before_install:
  - yarn add global binci

install:
  - binci install

script:
  - binci test
  
after_success:
  - sudo chmod -R 777 node_modules/ && sudo chmod -R 777 ~/.npm
  - yarn global add codecov
  - codecov -f coverage/lcov.info
  

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn global add pkg
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: yarn run build
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: binci.technologyadvice.com
    local-dir: bin
    acl: public_read
    on:
      branch: master
  
